### ISSUE TITLE
Implementing no signal

### ISSUE THREAD

**Issue by nealjane** [djwasser/M3iPiZeroW#2]
How are you implementing the no signal from the bike to app?

I recall you had issues due to having older software version on your bike (signal once per 2 seconds)  are you using 7 seconds still from gymnstcn?

couldn’t see anything when I had a quick scan through..

I’m just curious to why you just didn’t use gymnticon? I’ve built a few and I’ve had a couple of users who have the power drop after 10 seconds….I remember you had issues with dropouts - and I think they’re on the older software versions (as you) - 2015 bikes.

**Comment by djwasser** [comment]
@nealjane
I have not had issues with power drop outs, though I have seen the reports from others.  I do have the latest Keiser M3i, so that was not me either.  I use (stole!) the technique that @hypermoose uses for maintaining regular updates to Zwift even when there is a gap in data from the M3i (i would have to go back to the code to see exactly how it is done, but basically it just ensures that data is transmitted every second or soemthing like that).  

I ended up not using Gymnasticon because my initial experience with using it was that it would work for one or two sessions and then would stop providing a signal.  Also, I never liked that Gymnasticon "faked" the cadence while @hypermoose used the FTMS service which provides the cadence directly as read from the M3i.  Rather than dig into why Gymnasticon was not robust for me (and since the code was more complex to handle multiple types of bikes), I just rolled my own M3i-specific solution.  It has been up and running for a month+ so I am happy.  Even put in a little web server so I can see current state of M3i.  Since I share the spin bike with others in my house it quickly lets me know if it is in use or not.
